version: '3.12'
x-environment-defaults: &environment-defaults
  DEBUG: "False"
  POSTGRES_DB: "reviro"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: 5432

services:
  db:
    image: postgres:12.0-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reviro
#      - POSTGRES_HOST=localhost
    ports:
      - 5432:5432
  web:
    build: .
    container_name: reviro
    ports:
      - 8000:8000
    environment:
      <<: *environment-defaults
    depends_on:
      - db

volumes:
  postgres_data:
