# Generated by Django 4.2.10 on 2024-03-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Establishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created DateTime"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated DateTime"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                ("location", models.CharField(max_length=255, verbose_name="Location")),
                ("opening_hours", models.IntegerField(verbose_name="Opening Hours")),
            ],
            options={
                "verbose_name": "Establishment",
                "verbose_name_plural": "Establishments",
                "ordering": ("-created_at",),
            },
        ),
    ]
