# Generated by Django 4.2.10 on 2024-03-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("category", models.CharField(max_length=255, verbose_name="Category")),
                ("price", models.PositiveIntegerField(default=0, verbose_name="Price")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "availability_status",
                    models.BooleanField(
                        default=True, verbose_name="Availability Status"
                    ),
                ),
            ],
            options={
                "verbose_name": "Beverage",
                "verbose_name_plural": "Beverages",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Order Date"),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qrcode",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qrcodes/",
                        verbose_name="QR Code Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "QRCode",
                "verbose_name_plural": "QRCodes",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-month", "Month 1"),
                            ("3-month", "Month 3"),
                            ("6-month", "Month 6"),
                            ("1-year", "Year"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Subscription",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(auto_now_add=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(auto_now_add=True, verbose_name="End Date"),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Status")),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
    ]
